// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaGkWKTiPXEo7axwMNHrAFK1AuKbjukx0',
    appId: '1:612096482056:web:74b6824a97c5c455116abd',
    messagingSenderId: '612096482056',
    projectId: 'chitchat-84e1b',
    authDomain: 'chitchat-84e1b.firebaseapp.com',
    storageBucket: 'chitchat-84e1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdO6VQDEW5lo8coWcpjhu0rRhCuD3w9Ss',
    appId: '1:612096482056:android:64e0c3f3c98d919f116abd',
    messagingSenderId: '612096482056',
    projectId: 'chitchat-84e1b',
    storageBucket: 'chitchat-84e1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVEdwfkxup0PNCI4oeoc4fBeaR3ioHzs',
    appId: '1:612096482056:ios:8809aa4c0e3928ce116abd',
    messagingSenderId: '612096482056',
    projectId: 'chitchat-84e1b',
    storageBucket: 'chitchat-84e1b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVEdwfkxup0PNCI4oeoc4fBeaR3ioHzs',
    appId: '1:612096482056:ios:8809aa4c0e3928ce116abd',
    messagingSenderId: '612096482056',
    projectId: 'chitchat-84e1b',
    storageBucket: 'chitchat-84e1b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaGkWKTiPXEo7axwMNHrAFK1AuKbjukx0',
    appId: '1:612096482056:web:2a68f629177b2c25116abd',
    messagingSenderId: '612096482056',
    projectId: 'chitchat-84e1b',
    authDomain: 'chitchat-84e1b.firebaseapp.com',
    storageBucket: 'chitchat-84e1b.firebasestorage.app',
  );
}
